ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS price DECIMAL(10, 2),
  ADD COLUMN IF NOT EXISTS address_details VARCHAR(256),
  ADD COLUMN IF NOT EXISTS room_size INTEGER;